#include "esphome/core/log.h"
#include "irdaswitch.h"

// #include <driver/gpio.h>

namespace esphome {
namespace irdaswitch {

static const char *const TAG = "irdaswitch";

/**
 * special setup() method that will be called once to set up the component
 * at the time the setup() method is called, all the setters generated by the Python codebase have already run and the all fields are set for your class.
 * The setup() method should set up the communication interface for the component and check if communication works (if not, it should call mark_failed()).
 * 
 */
void irdaswitch::setup() {
    ESP_LOGI(TAG, "irdaswitch initialized.");

    WRITE_PERI_REG( 0x3FF6E020 , READ_PERI_REG(0x3FF6E020) | (1<<16) );  //UART_IRDA_EN  "Let there be light"
}

// Components should dump their configuration using ESP_LOGCONFIG at startup in dump_config()
void irdaswitch::dump_config() {
  ESP_LOGCONFIG(TAG, "irdaswitch:");
}

}  // namespace irdaswitch
}  // namespace esphome
